"""Smoke tests that run fully offline."""

from alum.backends import mesh_name
from alum.gateway import build_config, default_models_for, infer_provider, render_jsonc


def test_mesh_name_prefixes():
    assert mesh_name("alcf", "gpt-oss-120b") == "alcf:gpt-oss-120b"
    assert mesh_name("ollama", "gpt-oss:120b-cloud") == "ollama:gpt-oss-120b-cloud"
    assert mesh_name("asksage", "google-claude-sonnet-5") == "asksage:google-claude-sonnet-5"


def test_infer_provider_routes_by_prefix():
    assert infer_provider("argo:claude-opus-5", ["argo", "ollama"]) == "argo"
    assert infer_provider("argo:gpt-5.6-sol", ["argo", "ollama"]) == "argo"
    assert infer_provider("ollama:qwen3-8b", ["argo", "ollama"]) == "ollama"


def test_build_config_contains_server_and_models():
    models = {
        "alcf:gpt-oss-120b": "gpt-oss-120b",
        "ollama:gpt-oss-120b-cloud": "gpt-oss:120b-cloud",
    }
    cfg = build_config(["alcf", "ollama"], models, port=46701)
    assert cfg["server"]["port"] == 46701
    assert set(cfg["providers"]) == {"alcf", "ollama"}
    assert cfg["models"]["alcf:gpt-oss-120b"]["provider"] == "alcf"


def test_default_models_use_curated_fallbacks():
    models = default_models_for(["asksage"])
    assert models
    assert all(k.startswith("asksage:") for k in models)


def test_render_jsonc_is_commented():
    cfg = build_config(["ollama"], {"ollama:qwen3-8b": "qwen3:8b"})
    text = render_jsonc(cfg)
    assert text.startswith("// Generated by")
