"""Gateway config builder + launcher for llm-rosetta-gateway."""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

from platformdirs import user_config_dir

from alum.backends import DEFAULT_CAPABILITIES, GATEWAY_DEFAULT_PORT, REGISTRY, mesh_name

APP_NAME = "llm-rosetta-gateway"


def config_path(explicit: str | None = None) -> Path:
    if explicit:
        return Path(explicit).expanduser()
    return Path(user_config_dir(APP_NAME)) / "config.jsonc"


def build_config(
    provider_keys: list[str],
    models: dict[str, str],
    host: str = "127.0.0.1",
    port: int = GATEWAY_DEFAULT_PORT,
) -> dict:
    """Build a gateway config dict.

    - ``provider_keys``: backend keys from REGISTRY (e.g. ``["argo", "ollama"]``).
    - ``models``: mapping of ``mesh_name -> upstream_model``; provider is inferred
      from the mesh prefix (``argo:`` may belong to either argo backend — the
      caller's provider map wins, see ``build_model_entries``).
    """
    providers: dict = {}
    for key in provider_keys:
        providers.update(REGISTRY[key].gateway_providers)
    model_entries = build_model_entries(models, provider_keys)
    return {
        "providers": providers,
        "models": model_entries,
        "server": {"host": host, "port": port, "open_on_no_keys": True},
    }


def build_model_entries(models: dict[str, str], provider_keys: list[str]) -> dict:
    """Resolve each mesh model to the concrete gateway provider entry."""
    entries: dict = {}
    for mesh, upstream in models.items():
        provider = infer_provider(mesh, provider_keys)
        entries[mesh] = {
            "provider": provider,
            "upstream_model": upstream,
            "capabilities": list(DEFAULT_CAPABILITIES),
        }
    return entries


def infer_provider(mesh: str, provider_keys: list[str]) -> str:
    prefix = mesh.split(":", 1)[0] if ":" in mesh else ""
    candidates = {
        "argo": ["argo"] if "argo" in provider_keys else [],
        "alcf": ["alcf"] if "alcf" in provider_keys else [],
        "asksage": ["asksage"] if "asksage" in provider_keys else [],
        "ollama": ["ollama"] if "ollama" in provider_keys else [],
    }.get(prefix, [])
    if not candidates:
        # fall back to first selected provider (wizard guarantees non-empty)
        return _gateway_provider_name(provider_keys[0])
    return _gateway_provider_name(candidates[0])


def _gateway_provider_name(backend_key: str) -> str:
    providers = REGISTRY[backend_key].gateway_providers
    if backend_key == "asksage":
        return "AskSage"
    return next(iter(providers))


def default_models_for(provider_keys: list[str]) -> dict[str, str]:
    """Mesh-name -> upstream mapping using curated fallbacks."""
    from alum.backends import CURATED_MODELS

    out: dict[str, str] = {}
    for key in provider_keys:
        for upstream in CURATED_MODELS.get(key, []):
            mesh = mesh_name(key, upstream)
            # keep first winner on collision
            out.setdefault(mesh, upstream)
    return out


def render_jsonc(config: dict) -> str:
    body = json.dumps(config, indent=4)
    return (
        "// Generated by `alum setup`. Edit freely or re-run the wizard.\n"
        "// Port 46701 commemorates ANL's founding (1 July 1946).\n" + body + "\n"
    )


def write_config(config: dict, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        shutil.copy2(path, path.with_suffix(".jsonc.bak"))
    path.write_text(render_jsonc(config))
    return path


def launch_gateway(
    config: Path, host: str | None = None, port: int | None = None
) -> subprocess.Popen:
    cmd = ["llm-rosetta-gateway", "--config", str(config)]
    if host:
        cmd += ["--host", host]
    if port:
        cmd += ["--port", str(port)]
    return subprocess.Popen(cmd)
